// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package fakesql

import (
	"database/sql/driver"
	mock "github.com/stretchr/testify/mock"
)

// DriverContext is an autogenerated mock type for the DriverContext type
type DriverContext struct {
	mock.Mock
}

// OpenConnector provides a mock function with given fields: name
func (_m *DriverContext) OpenConnector(name string) (driver.Connector, error) {
	ret := _m.Called(name)

	var r0 driver.Connector
	if rf, ok := ret.Get(0).(func(string) driver.Connector); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Connector)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewDriverContext interface {
	mock.TestingT
	Cleanup(func())
}

// NewDriverContext creates a new instance of DriverContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDriverContext(t mockConstructorTestingTNewDriverContext) *DriverContext {
	mock := &DriverContext{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
