// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package fakesql

import (
	"database/sql/driver"
	mock "github.com/stretchr/testify/mock"
)

// NamedValueChecker is an autogenerated mock type for the NamedValueChecker type
type NamedValueChecker struct {
	mock.Mock
}

// CheckNamedValue provides a mock function with given fields: _a0
func (_m *NamedValueChecker) CheckNamedValue(_a0 *driver.NamedValue) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*driver.NamedValue) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewNamedValueChecker interface {
	mock.TestingT
	Cleanup(func())
}

// NewNamedValueChecker creates a new instance of NamedValueChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNamedValueChecker(t mockConstructorTestingTNewNamedValueChecker) *NamedValueChecker {
	mock := &NamedValueChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
