// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package fakesql

import (
	"database/sql/driver"
	mock "github.com/stretchr/testify/mock"
)

// RowsColumnTypeLength is an autogenerated mock type for the RowsColumnTypeLength type
type RowsColumnTypeLength struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *RowsColumnTypeLength) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ColumnTypeLength provides a mock function with given fields: index
func (_m *RowsColumnTypeLength) ColumnTypeLength(index int) (int64, bool) {
	ret := _m.Called(index)

	var r0 int64
	if rf, ok := ret.Get(0).(func(int) int64); ok {
		r0 = rf(index)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(int) bool); ok {
		r1 = rf(index)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Columns provides a mock function with given fields:
func (_m *RowsColumnTypeLength) Columns() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// Next provides a mock function with given fields: dest
func (_m *RowsColumnTypeLength) Next(dest []driver.Value) error {
	ret := _m.Called(dest)

	var r0 error
	if rf, ok := ret.Get(0).(func([]driver.Value) error); ok {
		r0 = rf(dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRowsColumnTypeLength interface {
	mock.TestingT
	Cleanup(func())
}

// NewRowsColumnTypeLength creates a new instance of RowsColumnTypeLength. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRowsColumnTypeLength(t mockConstructorTestingTNewRowsColumnTypeLength) *RowsColumnTypeLength {
	mock := &RowsColumnTypeLength{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
