// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package fakesql

import (
	context "context"

	"database/sql/driver"
	mock "github.com/stretchr/testify/mock"
)

// StmtQueryContext is an autogenerated mock type for the StmtQueryContext type
type StmtQueryContext struct {
	mock.Mock
}

// QueryContext provides a mock function with given fields: ctx, args
func (_m *StmtQueryContext) QueryContext(ctx context.Context, args []driver.NamedValue) (driver.Rows, error) {
	ret := _m.Called(ctx, args)

	var r0 driver.Rows
	if rf, ok := ret.Get(0).(func(context.Context, []driver.NamedValue) driver.Rows); ok {
		r0 = rf(ctx, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Rows)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []driver.NamedValue) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewStmtQueryContext interface {
	mock.TestingT
	Cleanup(func())
}

// NewStmtQueryContext creates a new instance of StmtQueryContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStmtQueryContext(t mockConstructorTestingTNewStmtQueryContext) *StmtQueryContext {
	mock := &StmtQueryContext{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
