package mocks

import (
	"github.com/kitstack/dbkit/specs"
	"github.com/stretchr/testify/mock"
)

// FakeCondition is an autogenerated mock type for the FakeCondition type
type FakeCondition struct {
	mock.Mock
}

// From provides a mock function with given fields:
func (_m *FakeCondition) From() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Operator provides a mock function with given fields:
func (_m *FakeCondition) Operator() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SetFrom provides a mock function with given fields: from
func (_m *FakeCondition) SetFrom(from string) specs.Condition {
	ret := _m.Called(from)

	var r0 specs.Condition
	if rf, ok := ret.Get(0).(func(string) specs.Condition); ok {
		r0 = rf(from)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(specs.Condition)
		}
	}

	return r0
}

// SetOperator provides a mock function with given fields: operator
func (_m *FakeCondition) SetOperator(operator string) specs.Condition {
	ret := _m.Called(operator)

	var r0 specs.Condition
	if rf, ok := ret.Get(0).(func(string) specs.Condition); ok {
		r0 = rf(operator)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(specs.Condition)
		}
	}

	return r0
}

// SetTo provides a mock function with given fields: to
func (_m *FakeCondition) SetTo(to interface{}) specs.Condition {
	ret := _m.Called(to)

	var r0 specs.Condition
	if rf, ok := ret.Get(0).(func(interface{}) specs.Condition); ok {
		r0 = rf(to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(specs.Condition)
		}
	}

	return r0
}

// To provides a mock function with given fields:
func (_m *FakeCondition) To() interface{} {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0)
		}
	}

	return r0
}

type mockConstructorTestingTNewCondition interface {
	mock.TestingT
	Cleanup(func())
}

// NewFakeCondition creates a new instance of FakeCondition. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFakeCondition(t mockConstructorTestingTNewCondition) *FakeCondition {
	fakeCondition := &FakeCondition{}
	fakeCondition.Mock.Test(t)

	t.Cleanup(func() { fakeCondition.AssertExpectations(t) })

	return fakeCondition
}
