package mocks

import (
	"github.com/lab210-dev/dbkit/specs"
	"github.com/stretchr/testify/mock"
)

// FakeDriverWhere is an autogenerated mock type for the FakeWhere type
type FakeDriverWhere struct {
	mock.Mock
}

// Formatted provides a mock function with given fields
func (_m *FakeDriverWhere) Formatted() (string, []any, error) {
	ret := _m.Called()

	var r0 string
	var r1 []any
	var r2 error
	if rf, ok := ret.Get(0).(func() (string, []any, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() []any); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]any)
		}
	}

	if rf, ok := ret.Get(2).(func() error); ok {
		r2 = rf()
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// From provides a mock function with given fields:
func (_m *FakeDriverWhere) From() specs.DriverField {
	ret := _m.Called()

	var r0 specs.DriverField
	if rf, ok := ret.Get(0).(func() specs.DriverField); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(specs.DriverField)
		}
	}

	return r0
}

// Operator provides a mock function with given fields:
func (_m *FakeDriverWhere) Operator() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SetFrom provides a mock function with given fields: from
func (_m *FakeDriverWhere) SetFrom(from specs.DriverField) specs.DriverWhere {
	ret := _m.Called(from)

	var r0 specs.DriverWhere
	if rf, ok := ret.Get(0).(func(specs.DriverField) specs.DriverWhere); ok {
		r0 = rf(from)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(specs.DriverWhere)
		}
	}

	return r0
}

// SetOperator provides a mock function with given fields: operator
func (_m *FakeDriverWhere) SetOperator(operator string) specs.DriverWhere {
	ret := _m.Called(operator)

	var r0 specs.DriverWhere
	if rf, ok := ret.Get(0).(func(string) specs.DriverWhere); ok {
		r0 = rf(operator)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(specs.DriverWhere)
		}
	}

	return r0
}

// SetTo provides a mock function with given fields: to
func (_m *FakeDriverWhere) SetTo(to any) specs.DriverWhere {
	ret := _m.Called(to)

	var r0 specs.DriverWhere
	if rf, ok := ret.Get(0).(func(any) specs.DriverWhere); ok {
		r0 = rf(to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(specs.DriverWhere)
		}
	}

	return r0
}

// To provides a mock function with given fields:
func (_m *FakeDriverWhere) To() any {
	ret := _m.Called()

	var r0 any
	if rf, ok := ret.Get(0).(func() any); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0)
		}
	}

	return r0
}

type mockConstructorTestingTNewWhere interface {
	mock.TestingT
	Cleanup(func())
}

// NewFakeDriverWhere creates a new instance of FakeWhere. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFakeDriverWhere(t mockConstructorTestingTNewWhere) *FakeDriverWhere {
	fakeDriverWhere := &FakeDriverWhere{}
	fakeDriverWhere.Mock.Test(t)

	t.Cleanup(func() { fakeDriverWhere.AssertExpectations(t) })

	return fakeDriverWhere
}
