package mocks

import (
	"github.com/kitstack/dbkit/specs"
	"github.com/stretchr/testify/mock"
	"reflect"
)

// FakeModelDefinition is an autogenerated mock type for the FakeModelDefinition type
type FakeModelDefinition struct {
	mock.Mock
}

// Copy provides a mock function with given fields:
func (_m *FakeModelDefinition) Copy() specs.Model {
	ret := _m.Called()

	var r0 specs.Model
	if rf, ok := ret.Get(0).(func() specs.Model); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(specs.Model)
		}
	}

	return r0
}

// Counter provides a mock function with given fields:
func (_m *FakeModelDefinition) Counter() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// DatabaseName provides a mock function with given fields:
func (_m *FakeModelDefinition) DatabaseName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// FieldByName provides a mock function with given fields:
func (_m *FakeModelDefinition) FieldByName() map[string]specs.FieldDefinition {
	ret := _m.Called()

	var r0 map[string]specs.FieldDefinition
	if rf, ok := ret.Get(0).(func() map[string]specs.FieldDefinition); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]specs.FieldDefinition)
		}
	}

	return r0
}

// Fields provides a mock function with given fields:
func (_m *FakeModelDefinition) Fields() []specs.FieldDefinition {
	ret := _m.Called()

	var r0 []specs.FieldDefinition
	if rf, ok := ret.Get(0).(func() []specs.FieldDefinition); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]specs.FieldDefinition)
		}
	}

	return r0
}

// FromField provides a mock function with given fields:
func (_m *FakeModelDefinition) FromField() specs.FieldDefinition {
	ret := _m.Called()

	var r0 specs.FieldDefinition
	if rf, ok := ret.Get(0).(func() specs.FieldDefinition); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(specs.FieldDefinition)
		}
	}

	return r0
}

// GetFieldByColumn provides a mock function with given fields: column
func (_m *FakeModelDefinition) GetFieldByColumn(column string) (specs.FieldDefinition, specs.ErrFieldNoFoundByColumn) {
	ret := _m.Called(column)

	var r0 specs.FieldDefinition
	var r1 specs.ErrFieldNoFoundByColumn
	if rf, ok := ret.Get(0).(func(string) (specs.FieldDefinition, specs.ErrFieldNoFoundByColumn)); ok {
		return rf(column)
	}
	if rf, ok := ret.Get(0).(func(string) specs.FieldDefinition); ok {
		r0 = rf(column)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(specs.FieldDefinition)
		}
	}

	if rf, ok := ret.Get(1).(func(string) specs.ErrFieldNoFoundByColumn); ok {
		r1 = rf(column)
	} else {
		r1 = ret.Get(1).(specs.ErrFieldNoFoundByColumn)
	}

	return r0, r1
}

// GetFieldByName provides a mock function with given fields: name
func (_m *FakeModelDefinition) GetFieldByName(name string) (specs.FieldDefinition, specs.ErrNotFoundError) {
	ret := _m.Called(name)

	var r0 specs.FieldDefinition
	var r1 specs.ErrNotFoundError
	if rf, ok := ret.Get(0).(func(string) (specs.FieldDefinition, specs.ErrNotFoundError)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) specs.FieldDefinition); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(specs.FieldDefinition)
		}
	}

	if rf, ok := ret.Get(1).(func(string) specs.ErrNotFoundError); ok {
		r1 = rf(name)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(specs.ErrNotFoundError)
		}
	}

	return r0, r1
}

// GetPrimaryField provides a mock function with given fields:
func (_m *FakeModelDefinition) GetPrimaryField() (specs.FieldDefinition, specs.ErrPrimaryFieldNotFound) {
	ret := _m.Called()

	var r0 specs.FieldDefinition
	var r1 specs.ErrPrimaryFieldNotFound
	if rf, ok := ret.Get(0).(func() (specs.FieldDefinition, specs.ErrPrimaryFieldNotFound)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() specs.FieldDefinition); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(specs.FieldDefinition)
		}
	}

	if rf, ok := ret.Get(1).(func() specs.ErrPrimaryFieldNotFound); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(specs.ErrPrimaryFieldNotFound)
		}
	}

	return r0, r1
}

// Index provides a mock function with given fields:
func (_m *FakeModelDefinition) Index() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// ModelOrigin provides a mock function with given fields:
func (_m *FakeModelDefinition) ModelOrigin() reflect.Value {
	ret := _m.Called()

	var r0 reflect.Value
	if rf, ok := ret.Get(0).(func() reflect.Value); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(reflect.Value)
	}

	return r0
}

// ModelValue provides a mock function with given fields:
func (_m *FakeModelDefinition) ModelValue() reflect.Value {
	ret := _m.Called()

	var r0 reflect.Value
	if rf, ok := ret.Get(0).(func() reflect.Value); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(reflect.Value)
	}

	return r0
}

// TypeName provides a mock function with given fields:
func (_m *FakeModelDefinition) TypeName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Parse provides a mock function with given fields:
func (_m *FakeModelDefinition) Parse() specs.ModelDefinition {
	ret := _m.Called()

	var r0 specs.ModelDefinition
	if rf, ok := ret.Get(0).(func() specs.ModelDefinition); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(specs.ModelDefinition)
		}
	}

	return r0
}

// SetFromField provides a mock function with given fields: fromField
func (_m *FakeModelDefinition) SetFromField(fromField specs.FieldDefinition) specs.ModelDefinition {
	ret := _m.Called(fromField)

	var r0 specs.ModelDefinition
	if rf, ok := ret.Get(0).(func(specs.FieldDefinition) specs.ModelDefinition); ok {
		r0 = rf(fromField)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(specs.ModelDefinition)
		}
	}

	return r0
}

// SetIndex provides a mock function with given fields: index
func (_m *FakeModelDefinition) SetIndex(index int) specs.ModelDefinition {
	ret := _m.Called(index)

	var r0 specs.ModelDefinition
	if rf, ok := ret.Get(0).(func(int) specs.ModelDefinition); ok {
		r0 = rf(index)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(specs.ModelDefinition)
		}
	}

	return r0
}

// TableName provides a mock function with given fields:
func (_m *FakeModelDefinition) TableName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewModelDefinition interface {
	mock.TestingT
	Cleanup(func())
}

// NewFakeModelDefinition creates a new instance of FakeModelDefinition. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFakeModelDefinition(t mockConstructorTestingTNewModelDefinition) *FakeModelDefinition {
	fakeModelDefinition := &FakeModelDefinition{}
	fakeModelDefinition.Mock.Test(t)

	t.Cleanup(func() { fakeModelDefinition.AssertExpectations(t) })

	return fakeModelDefinition
}
