package mocks

import (
	"github.com/kitstack/dbkit/specs"
	"github.com/stretchr/testify/mock"
)

// FakeNewSubBuilder is an autogenerated mock type for the FakeNewSubBuilder type
type FakeNewSubBuilder[T specs.Model] struct {
	mock.Mock
}

// NewSubBuilder provides a mock function with given fields:
func (_m *FakeNewSubBuilder[T]) NewSubBuilder() specs.SubBuilder[T] {
	ret := _m.Called()

	var r0 specs.SubBuilder[T]
	if rf, ok := ret.Get(0).(func() specs.SubBuilder[T]); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(specs.SubBuilder[T])
		}
	}

	return r0
}

type mockConstructorTestingTNewNewSubBuilder interface {
	mock.TestingT
	Cleanup(func())
}

// NewFakeNewSubBuilder creates a new instance of FakeNewSubBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFakeNewSubBuilder[T specs.Model](t mockConstructorTestingTNewNewSubBuilder) *FakeNewSubBuilder[T] {
	fakeSubBuilder := &FakeNewSubBuilder[T]{}
	fakeSubBuilder.Mock.Test(t)

	t.Cleanup(func() { fakeSubBuilder.AssertExpectations(t) })

	return fakeSubBuilder
}
