// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	"github.com/kitstack/dbkit/specs"
	"github.com/stretchr/testify/mock"
)

// FakeSubBuilderJob is an autogenerated mock type for the FakeSubBuilderJob type
type FakeSubBuilderJob[T specs.Model] struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *FakeSubBuilderJob[T]) Execute() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewSubBuilderJob interface {
	mock.TestingT
	Cleanup(func())
}

// FakeNewSubBuilderJob creates a new instance of FakeSubBuilderJob. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFakeSubBuilderJob[T specs.Model](t mockConstructorTestingTNewSubBuilderJob) *FakeSubBuilderJob[T] {
	fakeSubBuilderJob := &FakeSubBuilderJob[T]{}
	fakeSubBuilderJob.Mock.Test(t)

	t.Cleanup(func() { fakeSubBuilderJob.AssertExpectations(t) })

	return fakeSubBuilderJob
}
