// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package fakesql

import (
	"database/sql/driver"
	mock "github.com/stretchr/testify/mock"
)

// RowsColumnTypeNullable is an autogenerated mock type for the RowsColumnTypeNullable type
type RowsColumnTypeNullable struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *RowsColumnTypeNullable) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ColumnTypeNullable provides a mock function with given fields: index
func (_m *RowsColumnTypeNullable) ColumnTypeNullable(index int) (bool, bool) {
	ret := _m.Called(index)

	var r0 bool
	if rf, ok := ret.Get(0).(func(int) bool); ok {
		r0 = rf(index)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(int) bool); ok {
		r1 = rf(index)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Columns provides a mock function with given fields:
func (_m *RowsColumnTypeNullable) Columns() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// Next provides a mock function with given fields: dest
func (_m *RowsColumnTypeNullable) Next(dest []driver.Value) error {
	ret := _m.Called(dest)

	var r0 error
	if rf, ok := ret.Get(0).(func([]driver.Value) error); ok {
		r0 = rf(dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRowsColumnTypeNullable interface {
	mock.TestingT
	Cleanup(func())
}

// NewRowsColumnTypeNullable creates a new instance of RowsColumnTypeNullable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRowsColumnTypeNullable(t mockConstructorTestingTNewRowsColumnTypeNullable) *RowsColumnTypeNullable {
	mock := &RowsColumnTypeNullable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
