// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package fakesql

import (
	"database/sql/driver"
	mock "github.com/stretchr/testify/mock"
)

// RowsColumnTypePrecisionScale is an autogenerated mock type for the RowsColumnTypePrecisionScale type
type RowsColumnTypePrecisionScale struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *RowsColumnTypePrecisionScale) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ColumnTypePrecisionScale provides a mock function with given fields: index
func (_m *RowsColumnTypePrecisionScale) ColumnTypePrecisionScale(index int) (int64, int64, bool) {
	ret := _m.Called(index)

	var r0 int64
	if rf, ok := ret.Get(0).(func(int) int64); ok {
		r0 = rf(index)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 int64
	if rf, ok := ret.Get(1).(func(int) int64); ok {
		r1 = rf(index)
	} else {
		r1 = ret.Get(1).(int64)
	}

	var r2 bool
	if rf, ok := ret.Get(2).(func(int) bool); ok {
		r2 = rf(index)
	} else {
		r2 = ret.Get(2).(bool)
	}

	return r0, r1, r2
}

// Columns provides a mock function with given fields:
func (_m *RowsColumnTypePrecisionScale) Columns() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// Next provides a mock function with given fields: dest
func (_m *RowsColumnTypePrecisionScale) Next(dest []driver.Value) error {
	ret := _m.Called(dest)

	var r0 error
	if rf, ok := ret.Get(0).(func([]driver.Value) error); ok {
		r0 = rf(dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRowsColumnTypePrecisionScale interface {
	mock.TestingT
	Cleanup(func())
}

// NewRowsColumnTypePrecisionScale creates a new instance of RowsColumnTypePrecisionScale. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRowsColumnTypePrecisionScale(t mockConstructorTestingTNewRowsColumnTypePrecisionScale) *RowsColumnTypePrecisionScale {
	mock := &RowsColumnTypePrecisionScale{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
