// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package fakesql

import (
	"database/sql/driver"
	mock "github.com/stretchr/testify/mock"
)

// RowsColumnTypeDatabaseTypeName is an autogenerated mock type for the RowsColumnTypeDatabaseTypeName type
type RowsColumnTypeDatabaseTypeName struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *RowsColumnTypeDatabaseTypeName) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ColumnTypeDatabaseTypeName provides a mock function with given fields: index
func (_m *RowsColumnTypeDatabaseTypeName) ColumnTypeDatabaseTypeName(index int) string {
	ret := _m.Called(index)

	var r0 string
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(index)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Columns provides a mock function with given fields:
func (_m *RowsColumnTypeDatabaseTypeName) Columns() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// Next provides a mock function with given fields: dest
func (_m *RowsColumnTypeDatabaseTypeName) Next(dest []driver.Value) error {
	ret := _m.Called(dest)

	var r0 error
	if rf, ok := ret.Get(0).(func([]driver.Value) error); ok {
		r0 = rf(dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRowsColumnTypeDatabaseTypeName interface {
	mock.TestingT
	Cleanup(func())
}

// NewRowsColumnTypeDatabaseTypeName creates a new instance of RowsColumnTypeDatabaseTypeName. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRowsColumnTypeDatabaseTypeName(t mockConstructorTestingTNewRowsColumnTypeDatabaseTypeName) *RowsColumnTypeDatabaseTypeName {
	mock := &RowsColumnTypeDatabaseTypeName{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
