// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package fakesql

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// SessionResetter is an autogenerated mock type for the SessionResetter type
type SessionResetter struct {
	mock.Mock
}

// ResetSession provides a mock function with given fields: ctx
func (_m *SessionResetter) ResetSession(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewSessionResetter interface {
	mock.TestingT
	Cleanup(func())
}

// NewSessionResetter creates a new instance of SessionResetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSessionResetter(t mockConstructorTestingTNewSessionResetter) *SessionResetter {
	mock := &SessionResetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
