// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package fakesql

import (
	"database/sql/driver"
	mock "github.com/stretchr/testify/mock"
)

// ValueConverter is an autogenerated mock type for the ValueConverter type
type ValueConverter struct {
	mock.Mock
}

// ConvertValue provides a mock function with given fields: v
func (_m *ValueConverter) ConvertValue(v interface{}) (driver.Value, error) {
	ret := _m.Called(v)

	var r0 driver.Value
	if rf, ok := ret.Get(0).(func(interface{}) driver.Value); ok {
		r0 = rf(v)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Value)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(v)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewValueConverter interface {
	mock.TestingT
	Cleanup(func())
}

// NewValueConverter creates a new instance of ValueConverter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewValueConverter(t mockConstructorTestingTNewValueConverter) *ValueConverter {
	mock := &ValueConverter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
