// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package fakesql

import (
	"database/sql/driver"
	mock "github.com/stretchr/testify/mock"
)

// Execer is an autogenerated mock type for the Execer type
type Execer struct {
	mock.Mock
}

// Exec provides a mock function with given fields: query, args
func (_m *Execer) Exec(query string, args []driver.Value) (driver.Result, error) {
	ret := _m.Called(query, args)

	var r0 driver.Result
	if rf, ok := ret.Get(0).(func(string, []driver.Value) driver.Result); ok {
		r0 = rf(query, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Result)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, []driver.Value) error); ok {
		r1 = rf(query, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewExecer interface {
	mock.TestingT
	Cleanup(func())
}

// NewExecer creates a new instance of Execer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewExecer(t mockConstructorTestingTNewExecer) *Execer {
	mock := &Execer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
