// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package fakesql

import (
	"database/sql/driver"
	mock "github.com/stretchr/testify/mock"
)

// Queryer is an autogenerated mock type for the Queryer type
type Queryer struct {
	mock.Mock
}

// Query provides a mock function with given fields: query, args
func (_m *Queryer) Query(query string, args []driver.Value) (driver.Rows, error) {
	ret := _m.Called(query, args)

	var r0 driver.Rows
	if rf, ok := ret.Get(0).(func(string, []driver.Value) driver.Rows); ok {
		r0 = rf(query, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Rows)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, []driver.Value) error); ok {
		r1 = rf(query, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewQueryer interface {
	mock.TestingT
	Cleanup(func())
}

// NewQueryer creates a new instance of Queryer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewQueryer(t mockConstructorTestingTNewQueryer) *Queryer {
	mock := &Queryer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
