name: acceptance

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Start containers
        run: make up

      - name: Run acceptance tests
        run: make acceptance

      - name: Stop containers
        if: always()
        run: make down