name: Acceptance

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      - run: go run ./build/ci